#端口
server:
  port: 8060

mvc:
  static-path-pattern: classpath:/static/**

spring:
  #静态文件位置配置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  #数据库配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/cmain
    username: root
    password: lin000
    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml,classpath:mybatis/chat/*.xml

#打印sql日志
logging:
  level:
    com.app.appmain.chat.dao:  debug

